# This workflow will Rebuild SNT Docs triggered when changes to pyton or documentation related files are intended.

name: Rebuild SNT Docs
on:
  push:
    paths: 
      - '**.py'
      - '**/*docs/**'
      - '**/requirements.txt'
  pull_request:
    paths:
      - '**.py'
      - '**/*docs/**'
      - '**/requirements.txt'   

jobs:
  emodpy-snt-docs-rebuild:

    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
    # Environment Setup
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
          python-version: 3.8 
          
    - name: Install emodpy-snt requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple

    - name: Install the emodpy-snt package
      run: |
        pip install -e . --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple

    - name: Install documentation build requirements
      run: |
        pip install -r docs/requirements.txt --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple

    - name: Build docs - html - no break
      working-directory: 'docs'
      run: |
        make clean
        make htmlnobreak
        
   # This check won't run until issue below is addressed:
   # https://github.com/InstituteforDiseaseModeling/emodpy-malaria/issues/284
    - name: Build docs linkcheck - disabled
      working-directory: 'docs'
      run: |
        echo make linkcheck
        
